version: '3.8'

services:
  rag-service:
    build: .
    container_name: cf-rag-service
    ports:
      - "8000:8000"
    environment:
      - RAG_HOST=0.0.0.0
      - RAG_PORT=8000
      - RAG_WORKERS=1
      - RAG_LOG_LEVEL=INFO
      - RAG_REDIS_URL=redis://redis:6379
      # API Keys - set these in .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - rag-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cf-rag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rag-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  rag-network:
    driver: bridge

volumes:
  redis-data: