name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 46.202.177.230 # Replace with your VPS IP
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Store your SSH private key as a secret in GitHub
          script: |
            # Create deployment directory if it doesn't exist
            mkdir -p /var/www/pb-cline

            # Copy the build output to the VPS
            scp -r dist/* root@46.202.177.230:/var/www/pb-cline/

            # Option A: If using Node backend, restart PM2
            pm2 restart ecosystem.config.cjs

            # Option B: If serving static files directly, reload Nginx
            sudo nginx -t && sudo systemctl reload nginx